# Generated by Django 2.2 on 2019-05-29 15:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdziany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprawdzian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_nauczyciela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprawdziany.Nauczyciel')),
            ],
        ),
    ]
