# Generated by Django 2.2 on 2019-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdziany', '0002_sprawdzian'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprawdzian',
            name='klasa',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
