# Generated by Django 2.2 on 2019-05-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprawdziany', '0004_przedmiot'),
    ]

    operations = [
        migrations.AddField(
            model_name='nauczyciel',
            name='id_przedmiotu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sprawdziany.Przedmiot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprawdzian',
            name='id_przedmiotu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sprawdziany.Przedmiot'),
            preserve_default=False,
        ),
    ]
